name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: '16.5'
    - name: Run Scripts
      run: Build.cmd
      shell: cmd
    - name: Upload Files
      uses: actions/upload-artifact@v2
      with:
        name: Release
        path: "Release.zip"
    - name: Make a release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "Auto"
        prerelease: true
        title: "Auto Build"
        files: |
          Release.zip
